# Permalinks
permalink:        pretty

# Setup
title:            Angela & Silvester reisen... Aber jetzt!
tagline:          Ein Reiseblog
url:              http://whataboutas.github.io
paginate:         5
baseurl:          http://whataboutas.github.io/
author:
  name:           Angela & Silvester
  url:            
  email:     
  
# This is the list of pages to include in the header of the website.
pages_list:       
  Archiv: 'http://whataboutas.github.io/archive/'



# Custom vars
version:          1.0.0
github:
  repo:           
highlighter: rouge
markdown: redcarpet

excerpt_separator: <!--more-->  # you can specify your own separator, of course.
