# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            What about Angela & Silvester?
tagline:          Ein Reiseblog
url:              http://blog.whataboutas.at
paginate:         5
baseurl:          /
author:
  name:           Angela & Silvester
  url:            
  email:     
  
# This is the list of pages to include in the header of the website.
pages_list:       
  Archiv: '/archive/'



# Custom vars
version:          1.0.0
github:
  repo:           
highlighter: pygments
markdown: redcarpet